// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace taaksi.Models;

public partial class Discount
{
    public int DiscountId { get; set; }

    public string DiscountCode { get; set; }

    public decimal? DiscountAmount { get; set; }

    public DateTime? ValidFrom { get; set; }

    public DateTime? ValidTo { get; set; }
}