// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace taaksi.Models;

public partial class DriverRating
{
    public int RatingId { get; set; }

    public int? DriverId { get; set; }

    public decimal? Rating { get; set; }

    public string Comment { get; set; }

    public virtual Driver Driver { get; set; }
}