// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace taaksi.Models;

public partial class Mileage
{
    public int MileageId { get; set; }

    public int? CarId { get; set; }

    public decimal? Mileage1 { get; set; }

    public DateTime? DateRecorded { get; set; }

    public virtual Car Car { get; set; }
}