// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace taaksi.Models;

public partial class PaymentTransaction
{
    public int TransactionId { get; set; }

    public int? CustomerId { get; set; }

    public int? TripId { get; set; }

    public decimal? Amount { get; set; }

    public DateTime? PaymentDate { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Trip Trip { get; set; }
}