// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace taaksi.Models;

public partial class PricingPolicy
{
    public int PolicyId { get; set; }

    public string CarType { get; set; }

    public decimal? BaseFare { get; set; }

    public decimal? PerMileRate { get; set; }
}