// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace taaksi.Models;

public partial class RentalRequest
{
    public int RequestId { get; set; }

    public int? CustomerId { get; set; }

    public string CarType { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public bool? IsApproved { get; set; }

    public virtual Customer Customer { get; set; }
}