// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace taaksi.Models;

public partial class Trip
{
    public int TripId { get; set; }

    public int? DriverId { get; set; }

    public int? CustomerId { get; set; }

    public int? CarId { get; set; }

    public DateTime? StartTime { get; set; }

    public DateTime? EndTime { get; set; }

    public decimal? Fare { get; set; }

    public virtual Car Car { get; set; }

    public virtual Customer Customer { get; set; }

    public virtual Driver Driver { get; set; }

    public virtual ICollection<PaymentTransaction> PaymentTransactions { get; set; } = new List<PaymentTransaction>();
}